USE UNIVER;

--1
SELECT A.AUDITORIUM, AT.AUDITORIUM_TYPENAME
FROM AUDITORIUM A
INNER JOIN AUDITORIUM_TYPE AT ON A.AUDITORIUM_TYPE = AT.AUDITORIUM_TYPE;

--2
SELECT A.AUDITORIUM, AT.AUDITORIUM_TYPENAME
FROM AUDITORIUM A
INNER JOIN AUDITORIUM_TYPE AT ON A.AUDITORIUM_TYPE = AT.AUDITORIUM_TYPE
WHERE AT.AUDITORIUM_TYPENAME LIKE '%компьютер%';

--3
SELECT 
    F.FACULTY_NAME AS Факультет, 
    P.PULPIT_NAME AS Кафедра, 
    PR.PROFESSION_NAME AS Специальность, 
    S.SUBJECT_NAME AS Дисциплина, 
    ST.NAME AS Имя_Студента, 
    CASE 
        WHEN PRG.NOTE = 6 THEN 'шесть'
        WHEN PRG.NOTE = 7 THEN 'семь'
        WHEN PRG.NOTE = 8 THEN 'восемь'
    END AS Оценка
FROM 
    PROGRESS PRG
INNER JOIN STUDENT ST ON PRG.IDSTUDENT = ST.IDSTUDENT
INNER JOIN GROUPS G ON ST.IDGROUP = G.IDGROUP
INNER JOIN SUBJECT S ON PRG.SUBJECT = S.SUBJECT
INNER JOIN PULPIT P ON S.PULPIT = P.PULPIT
INNER JOIN FACULTY F ON P.FACULTY = F.FACULTY
INNER JOIN PROFESSION PR ON G.PROFESSION = PR.PROFESSION
WHERE 
    PRG.NOTE BETWEEN 6 AND 8
ORDER BY 
    PRG.NOTE DESC;

--4
SELECT 
    P.PULPIT_NAME AS Кафедра, 
    ISNULL(T.TEACHER_NAME, '***') AS Преподаватель
FROM 
    PULPIT P
LEFT OUTER JOIN TEACHER T ON P.PULPIT = T.PULPIT;

--5
--SELECT *
--FROM Table1
--FULL OUTER JOIN Table2 ON Table1.ID = Table2.ID
--WHERE Table2.ID IS NULL;

--SELECT *
--FROM Table1
--FULL OUTER JOIN Table2 ON Table1.ID = Table2.ID
--WHERE Table1.ID IS NULL;

--SELECT *
--FROM Table1
--FULL OUTER JOIN Table2 ON Table1.ID = Table2.ID;

--6
SELECT A.AUDITORIUM, AT.AUDITORIUM_TYPENAME
FROM AUDITORIUM A
CROSS JOIN AUDITORIUM_TYPE AT
WHERE A.AUDITORIUM_TYPE = AT.AUDITORIUM_TYPE;




