CREATE DATABASE KONTROLNAYA;

USE KONTROLNAYA;

CREATE TABLE STUDENT 
(
    IDST INT IDENTITY(1,1) PRIMARY KEY,
    IDGROUP INT NOT NULL,
    NAME NVARCHAR(100) NOT NULL,
    BDAY DATE NOT NULL
);

CREATE TABLE SESSIA 
(
    SUBJ INT,
    IDST INT FOREIGN KEY REFERENCES STUDENT(IDST),
    PDATE DATE,
    NOTE INT CHECK (NOTE BETWEEN 1 AND 10)
);


INSERT INTO STUDENT (IDGROUP, NAME, BDAY) 
VALUES (1, 'Иванов Иван Иванович', '2000-01-01'), 
       (2, 'Петров Петр Петрович', '2000-02-02'), 
       (3, 'Сидоров Сидор Сидорович', '2000-03-03'), 
       (4, 'Алексеев Алексей Алексеевич', '2000-04-04');

INSERT INTO SESSIA (SUBJ, IDST, PDATE, NOTE) 
VALUES (1, 1, '2022-01-01', 5), 
       (2, 2, '2022-02-02', 6), 
       (3, 3, '2022-03-03', 7), 
       (4, 4, '2022-04-04', 8);

SELECT PDATE AS 'Дата экзамена', SUBJ AS 'Дисциплина', NAME AS 'Студент', NOTE AS 'Оценка'
FROM SESSIA 
INNER JOIN STUDENT ON SESSIA.IDST = STUDENT.IDST
WHERE NOTE BETWEEN 5 AND 7;

SELECT COUNT_NOTE, NOTE
FROM 
(
    SELECT COUNT(*) AS COUNT_NOTE, NOTE
    FROM SESSIA
    WHERE NOTE BETWEEN 5 AND 7
    GROUP BY NOTE
) AS SUBQUERY
ORDER BY NOTE DESC;
